import type { ClusterPageConfig } from '@/features/content/cluster-content-page.types';

export const webParaRestauranteBarArgentinaConfig: ClusterPageConfig = {
  slug: 'web-para-restaurante-bar-argentina',
  title: 'Web para restaurante o bar en Argentina',
  description: 'Que necesita una web para restaurante o bar en Argentina para atraer reservas, mostrar propuesta y convertir visitas en mesas.',
  keywords: 'web para restaurante argentina, web para bar argentina, pagina web restaurante argentina',
  eyebrow: 'Gastronomia',
  heroTitle: 'Web para restaurante o bar en Argentina',
  heroHighlight: 'para convertir visitas en reservas.',
  heroBody: 'En gastronomia, la web tiene que abrir el apetito y resolver rapido. Si no muestra propuesta, horarios y como reservar desde el celular, pierde mesas.',
  introTitle: 'La decision se toma rapido',
  introBody: 'Quien busca donde comer o tomar algo compara en minutos. Si la experiencia online no acompana, la reserva termina en otro lado aunque la propuesta sea buena.',
  primaryTitle: 'Que tiene que resolver una web gastronomica',
  primaryItems: [
    { title: 'Propuesta clara', description: 'Mostrar tipo de cocina, ambiente, ubicacion y diferenciales sin obligar a buscar demasiado.' },
    { title: 'Accion inmediata', description: 'Facilitar reserva, pedido o contacto desde el primer scroll y en cada pantalla clave.' },
    { title: 'Experiencia mobile', description: 'Priorizar fotos, horarios, mapa y CTA porque la mayor parte del trafico llega desde el telefono.' },
  ],
  asideTitle: 'Tu sitio acompana reservas?',
  asideBody: 'Podemos revisar si tu web hoy ayuda a llenar mesas o si solo funciona como una tarjeta digital.',
  asidePrimaryCta: 'Pedir diagn?stico para gastronom?a',
  issuesTitle: 'Lo que mas suele fallar',
  issuesItems: [
    'Menu, horarios o direccion poco visibles desde mobile.',
    'No dejar clara la propuesta del lugar en los primeros segundos.',
    'Reserva o contacto escondidos detras de demasiados pasos.',
  ],
  nextStepsTitle: 'Como mejorarlo',
  nextSteps: [
    { title: 'Ordenar la jerarquia', description: 'Poner primero lo que hace decidir: propuesta, ubicacion, horarios y accion.' },
    { title: 'Reducir friccion', description: 'Hacer simple reservar, pedir o escribir por WhatsApp segun el modelo del local.' },
    { title: 'Medir conversion', description: 'Entender que paginas y CTA generan reservas o consultas reales.' },
  ],
  closingTitle: 'Una buena web gastronomica no decora, vende',
  closingBody: 'Si el sitio transmite la experiencia y hace facil actuar, deja de ser una presencia pasiva y pasa a mover reservas.',
};

export const cartaDigitalQrRestauranteConfig: ClusterPageConfig = {
  slug: 'carta-digital-qr-restaurante',
  title: 'Carta digital QR para restaurante',
  description: 'Como plantear una carta digital QR para restaurante sin complicar la experiencia del cliente ni la operacion del local.',
  keywords: 'carta digital qr restaurante, menu qr restaurante argentina, carta digital para restaurante',
  eyebrow: 'Carta digital',
  heroTitle: 'Carta digital QR para restaurante',
  heroHighlight: 'sin romper la experiencia en mesa.',
  heroBody: 'Una carta QR no sirve por moda. Sirve cuando mejora actualizacion, lectura y acceso sin volver mas lenta la decision del cliente.',
  introTitle: 'Digitalizar no alcanza',
  introBody: 'Si el menu tarda, se ve mal o no ayuda a elegir, el QR suma friccion en vez de resolverla. La experiencia tiene que ser clara y rapida.',
  primaryTitle: 'Que deberia resolver una carta digital',
  primaryItems: [
    { title: 'Lectura simple', description: 'Cargar rapido, verse bien en mobile y organizar categorias sin esfuerzo.' },
    { title: 'Actualizacion agil', description: 'Permitir cambios de platos, precios o disponibilidad sin rehacer todo cada vez.' },
    { title: 'Contexto comercial', description: 'Destacar recomendados, combos o diferenciales para empujar ticket y decision.' },
  ],
  asideTitle: 'Tu carta QR ayuda o estorba?',
  asideBody: 'Podemos revisar si hoy tu menu digital acompana la experiencia del salon o genera abandono.',
  asidePrimaryCta: 'Pedir diagn?stico de carta digital',
  issuesTitle: 'Problemas frecuentes',
  issuesItems: [
    'PDF pesados o ilegibles desde el celular.',
    'Cartas desactualizadas que generan confusion en mesa.',
    'Experiencia sin estructura ni categorias claras.',
  ],
  nextStepsTitle: 'Que conviene ajustar',
  nextSteps: [
    { title: 'Elegir formato correcto', description: 'No siempre conviene un PDF; muchas veces hace falta una experiencia web simple.' },
    { title: 'Pensar la navegacion', description: 'Separar categorias, destacados y extras para que elegir sea facil.' },
    { title: 'Integrar operacion', description: 'Alinear menu digital con cambios reales del local y su forma de trabajo.' },
  ],
  closingTitle: 'Una buena carta QR reduce dudas y acelera pedidos',
  closingBody: 'Cuando el menu digital esta bien resuelto, mejora la experiencia del cliente y baja friccion operativa en el salon.',
};

export const reservasOnlineRestauranteConfig: ClusterPageConfig = {
  slug: 'reservas-online-restaurante',
  title: 'Reservas online para restaurante',
  description: 'Que tener en cuenta para implementar reservas online en un restaurante sin sumar caos al salon ni perder control.',
  keywords: 'reservas online restaurante, sistema reservas restaurante argentina, turnos restaurante online',
  eyebrow: 'Reservas online',
  heroTitle: 'Reservas online para restaurante',
  heroHighlight: 'sin perder control operativo.',
  heroBody: 'Tomar reservas online no es solo sumar un formulario. Tiene que respetar capacidad, horarios, turnos y confirmaciones para no romper el servicio.',
  introTitle: 'Reservar mejor es operar mejor',
  introBody: 'Si el flujo no acompana la realidad del local, aparecen mesas duplicadas, consultas manuales y friccion justo antes de la visita.',
  primaryTitle: 'Que deberia resolver un sistema de reservas',
  primaryItems: [
    { title: 'Disponibilidad real', description: 'Reflejar dias, horarios, cupos y reglas de ocupacion sin errores.' },
    { title: 'Confirmaciones claras', description: 'Enviar contexto util para bajar ausencias y evitar dudas de ultimo momento.' },
    { title: 'Experiencia simple', description: 'Permitir reservar rapido desde mobile sin formularios eternos.' },
  ],
  asideTitle: 'Conviene en tu caso?',
  asideBody: 'Podemos revisar si hoy reservas online te ayudarian a ordenar demanda o si primero hay que ajustar otra parte del proceso.',
  asidePrimaryCta: 'Pedir diagn?stico de reservas',
  issuesTitle: 'Donde suele romperse',
  issuesItems: [
    'Reservas que no respetan capacidad ni tiempos reales del salon.',
    'Falta de confirmaciones o recordatorios y aumento de no-shows.',
    'Flujos largos que hacen que el usuario abandone antes de reservar.',
  ],
  nextStepsTitle: 'Como bajarlo a tierra',
  nextSteps: [
    { title: 'Definir reglas de reserva', description: 'Antes de implementar, hay que ordenar cupos, horarios, tolerancias y excepciones.' },
    { title: 'Elegir flujo correcto', description: 'No todos los restaurantes necesitan el mismo nivel de automatizacion.' },
    { title: 'Conectar con captacion', description: 'La reserva tiene que integrarse con la web y los canales reales del negocio.' },
  ],
  closingTitle: 'Las reservas online sirven cuando respetan la operacion',
  closingBody: 'Si el sistema acompana como trabaja el local, mejora la experiencia del cliente y reduce caos interno.',
};
