import type { ClusterPageConfig } from '@/features/content/cluster-content-page.types';

export const webParaDentistasArgentinaConfig: ClusterPageConfig = {
  slug: 'web-para-dentistas-argentina',
  title: 'Web para dentistas en Argentina',
  description: 'Qué necesita una web para dentistas en Argentina para generar consultas, mostrar tratamientos y ordenar turnos.',
  keywords: 'web para dentistas argentina, pagina web odontologo argentina, sitio web odontologia argentina',
  eyebrow: 'Salud dental',
  heroTitle: 'Web para dentistas en Argentina',
  heroHighlight: 'para convertir visitas en consultas.',
  heroBody: 'Una clínica dental no necesita solo presencia online. Necesita confianza, claridad en tratamientos y una forma simple de pasar de interés a turno.',
  introTitle: 'La web no es un folleto',
  introBody: 'Cuando alguien busca un dentista, compara rápido. Si no entiende qué hacés, dónde atendés o cómo reservar, la consulta se pierde antes del contacto.',
  primaryTitle: 'Qué tiene que resolver una web dental',
  primaryItems: [
    { title: 'Tratamientos claros', description: 'Explicar servicios, especialidades y casos frecuentes sin llenar la página de tecnicismos.' },
    { title: 'Prueba de confianza', description: 'Mostrar equipo, consultorio, reseñas y señales que bajen ansiedad antes del primer turno.' },
    { title: 'Turnos simples', description: 'Hacer fácil reservar por WhatsApp, formulario o sistema según cómo opere el consultorio.' },
  ],
  asideTitle: '¿Querés revisar tu caso?',
  asideBody: 'Podemos ver si hoy tu sitio acompaña la captación de pacientes o si está frenando consultas.',
  asidePrimaryCta: 'Pedir diagnóstico para odontología',
  issuesTitle: 'Lo que más suele fallar',
  issuesItems: [
    'Páginas genéricas sin diferenciar tratamientos ni especialidad.',
    'Falta de confianza visual o mensaje poco claro para pacientes nuevos.',
    'Contacto escondido o proceso de turno confuso desde el celular.',
  ],
  nextStepsTitle: 'Cómo mejorarlo',
  nextSteps: [
    { title: 'Ordenar la propuesta', description: 'Definir qué servicios empujan más consultas y cómo se presentan.' },
    { title: 'Priorizar mobile', description: 'La mayoría de los pacientes llega desde el teléfono y decide rápido.' },
    { title: 'Medir contactos', description: 'Saber qué páginas y CTA están trayendo pacientes reales.' },
  ],
  closingTitle: 'Una clínica dental vende confianza antes del turno',
  closingBody: 'Si la web transmite claridad y hace simple el contacto, la consulta deja de depender solo de redes o recomendación.',
};

export const webParaPsicologosArgentinaConfig: ClusterPageConfig = {
  slug: 'web-para-psicologos-argentina',
  title: 'Web para psicólogos en Argentina',
  description: 'Cómo debería ser una web para psicólogos en Argentina para transmitir confianza, explicar enfoque y generar primeras consultas.',
  keywords: 'web para psicologos argentina, pagina web psicologo argentina, sitio web psicologia argentina',
  eyebrow: 'Salud mental',
  heroTitle: 'Web para psicólogos en Argentina',
  heroHighlight: 'para generar confianza antes del primer mensaje.',
  heroBody: 'En psicología, la primera impresión pesa mucho. Una buena web ayuda a explicar enfoque, modalidad y disponibilidad sin ruido.',
  introTitle: 'La decisión pasa por confianza',
  introBody: 'Quien busca terapia no quiere navegar una web fría o confusa. Necesita entender rápido si ese profesional puede ayudarlo y cómo contactarlo.',
  primaryTitle: 'Qué debería tener una web para psicología',
  primaryItems: [
    { title: 'Enfoque claro', description: 'Explicar especialidades, modalidad y tipo de acompañamiento sin lenguaje críptico.' },
    { title: 'Contacto humano', description: 'Facilitar primer paso con WhatsApp, formulario o agenda, sin fricción innecesaria.' },
    { title: 'Presencia profesional', description: 'Dar contexto, experiencia y tono correcto para bajar dudas iniciales.' },
  ],
  asideTitle: '¿Tu web transmite confianza?',
  asideBody: 'Podemos revisar si hoy tu sitio acompaña el primer contacto o genera distancia antes de escribir.',
  asidePrimaryCta: 'Pedir diagnóstico para psicología',
  issuesTitle: 'Errores frecuentes',
  issuesItems: [
    'Texto demasiado abstracto o genérico.',
    'No dejar claro si la atención es presencial, online o ambas.',
    'Formas de contacto escondidas o poco cómodas en mobile.',
  ],
  nextStepsTitle: 'Qué conviene ajustar',
  nextSteps: [
    { title: 'Aterrizar el mensaje', description: 'Hablarle a la persona que consulta, no a colegas del rubro.' },
    { title: 'Definir CTA principal', description: 'Elegir una acción simple: escribir, reservar o pedir información.' },
    { title: 'Mostrar contexto', description: 'Presentar experiencia, enfoque y modalidad con claridad.' },
  ],
  closingTitle: 'Una web para psicología tiene que acercar, no enfriar',
  closingBody: 'Cuando el sitio acompaña el momento emocional del usuario, la primera consulta se vuelve mucho más probable.',
};

export const webParaKinesiologoArgentinaConfig: ClusterPageConfig = {
  slug: 'web-para-kinesiologo-argentina',
  title: 'Web para kinesiólogo en Argentina',
  description: 'Qué necesita una web para kinesiólogo en Argentina para mostrar servicios, captar consultas y facilitar turnos.',
  keywords: 'web para kinesiologo argentina, pagina web kinesiologia argentina, sitio web kinesiólogo argentina',
  eyebrow: 'Rehabilitación',
  heroTitle: 'Web para kinesiólogo en Argentina',
  heroHighlight: 'para captar consultas y ordenar turnos.',
  heroBody: 'En kinesiología, la gente necesita entender rápido qué tratás, dónde atendés y cómo reservar sin vueltas.',
  introTitle: 'La web tiene que simplificar',
  introBody: 'Si el paciente llega con dolor o urgencia, no va a leer demasiado. Necesita confianza, especialidad visible y una forma simple de escribir o reservar.',
  primaryTitle: 'Qué debería resolver tu sitio',
  primaryItems: [
    { title: 'Servicios visibles', description: 'Mostrar lesiones, tratamientos, rehabilitación y modalidades sin esconder lo importante.' },
    { title: 'Ubicación y horarios', description: 'Dejar clara la atención presencial, domicilio o convenios si aplica.' },
    { title: 'Contacto inmediato', description: 'Resolver rápido el paso a WhatsApp o turnera desde el celular.' },
  ],
  asideTitle: '¿Tu sitio te trae pacientes?',
  asideBody: 'Podemos revisar si tu web hoy ayuda a convertir búsquedas en consultas o si solo existe.',
  asidePrimaryCta: 'Pedir diagnóstico para kinesiología',
  issuesTitle: 'Qué suele trabar consultas',
  issuesItems: [
    'No explicar bien qué lesiones o casos atendés.',
    'No mostrar ubicación, modalidad o cobertura desde el inicio.',
    'Depender de un formulario largo cuando el usuario quiere resolver rápido.',
  ],
  nextStepsTitle: 'Qué conviene hacer',
  nextSteps: [
    { title: 'Priorizar intención', description: 'Diseñar la home para quien quiere resolver un problema concreto.' },
    { title: 'Ordenar especialidades', description: 'Separar claramente rehabilitación, deportiva, postural u otras áreas.' },
    { title: 'Acortar contacto', description: 'Reducir pasos entre visita y mensaje.' },
  ],
  closingTitle: 'Si el paciente entiende rápido, consulta más rápido',
  closingBody: 'Una web clara y orientada a acción puede hacer la diferencia entre una visita perdida y un turno nuevo.',
};

export const turnosOnlineMedicosArgentinaConfig: ClusterPageConfig = {
  slug: 'turnos-online-medicos-argentina',
  title: 'Turnos online médicos en Argentina',
  description: 'Cómo implementar turnos online médicos en Argentina sin romper la operación del consultorio o clínica.',
  keywords: 'turnos online medicos argentina, sistema de turnos medicos argentina, reservas medicas online argentina',
  eyebrow: 'Turnos online',
  heroTitle: 'Turnos online médicos en Argentina',
  heroHighlight: 'sin sumar caos a la agenda.',
  heroBody: 'Digitalizar turnos no es solo poner un botón. Tiene que encajar con disponibilidad, confirmaciones, recordatorios y forma real de trabajo.',
  introTitle: 'El objetivo no es tener una agenda linda',
  introBody: 'El objetivo es reducir fricción para el paciente y menos trabajo manual para recepción o secretaría.',
  primaryTitle: 'Qué debería resolver un sistema de turnos',
  primaryItems: [
    { title: 'Disponibilidad real', description: 'Reflejar horarios, profesionales y reglas de agenda sin errores.' },
    { title: 'Confirmaciones claras', description: 'Evitar idas y vueltas con mensajes automáticos y contexto útil.' },
    { title: 'Experiencia simple', description: 'Permitir reservar desde el celular sin obligar a completar pasos innecesarios.' },
  ],
  asideTitle: '¿Conviene en tu caso?',
  asideBody: 'Podemos revisar si hoy un sistema de turnos te ahorra trabajo o si primero hay que ordenar otra parte de la operación.',
  asidePrimaryCta: 'Pedir diagnóstico de turnos online',
  issuesTitle: 'Dónde suele romperse',
  issuesItems: [
    'La agenda online no coincide con la disponibilidad real.',
    'No hay recordatorios ni seguimiento y aumentan ausencias.',
    'La web no explica qué profesional o práctica elegir.',
  ],
  nextStepsTitle: 'Cómo bajarlo a tierra',
  nextSteps: [
    { title: 'Definir reglas de agenda', description: 'Antes de implementar, hay que ordenar duración, buffers y excepciones.' },
    { title: 'Elegir flujo correcto', description: 'No todos los consultorios necesitan el mismo nivel de automatización.' },
    { title: 'Conectar con captación', description: 'La reserva tiene que estar integrada con la web y el canal de consulta principal.' },
  ],
  closingTitle: 'Los turnos online funcionan cuando respetan tu operación',
  closingBody: 'Si el sistema acompaña la realidad del consultorio, mejora la experiencia del paciente y baja la carga operativa.',
};
