import type { ClusterPageConfig } from '@/features/content/cluster-content-page.types';

export const webEstudioJuridicoArgentinaConfig: ClusterPageConfig = {
  slug: 'web-estudio-juridico-argentina',
  title: 'Web para estudio juridico en Argentina',
  description: 'Que necesita una web para estudio juridico en Argentina para transmitir confianza, explicar servicios y generar consultas calificadas.',
  keywords: 'web estudio juridico argentina, pagina web abogados argentina, sitio web estudio juridico',
  eyebrow: 'Profesionales',
  heroTitle: 'Web para estudio juridico en Argentina',
  heroHighlight: 'para generar confianza y consultas.',
  heroBody: 'Un estudio juridico no compite solo por aparecer. Compite por transmitir seriedad, especializacion y una forma clara de iniciar contacto sin friccion.',
  introTitle: 'La confianza se define rapido',
  introBody: 'Cuando alguien busca asesoria legal, necesita entender en segundos si el estudio trata su caso, como trabaja y por que vale la pena escribir.',
  primaryTitle: 'Que deberia resolver una web legal',
  primaryItems: [
    { title: 'Servicios claros', description: 'Explicar areas de practica, tipo de clientes y alcance sin tecnicismos innecesarios.' },
    { title: 'Autoridad profesional', description: 'Mostrar trayectoria, casos de experiencia y senales de confianza sin sobreactuar.' },
    { title: 'Contacto simple', description: 'Facilitar una consulta inicial por formulario o WhatsApp con el contexto justo.' },
  ],
  asideTitle: 'Tu sitio hoy acompana consultas?',
  asideBody: 'Podemos revisar si la web de tu estudio transmite seriedad y convierte interes en conversaciones reales.',
  asidePrimaryCta: 'Pedir diagnostico para estudio juridico',
  issuesTitle: 'Lo que suele fallar',
  issuesItems: [
    'Textos demasiado genericos o llenos de jerga legal.',
    'No dejar claro para que tipo de casos o clientes trabaja el estudio.',
    'Contacto escondido o sin una accion principal visible.',
  ],
  nextStepsTitle: 'Como mejorarlo',
  nextSteps: [
    { title: 'Definir foco', description: 'Ordenar areas de practica segun lo que mas consultas y cierres genera.' },
    { title: 'Bajar complejidad', description: 'Traducir servicios legales a lenguaje que un cliente potencial entienda rapido.' },
    { title: 'Medir demanda', description: 'Entender que paginas y CTA atraen consultas de mejor calidad.' },
  ],
  closingTitle: 'Una buena web legal no impresiona, convence',
  closingBody: 'Si el sitio transmite claridad y confianza, el estudio deja de depender solo de referidos y mejora su captacion.',
};

export const webContadorArgentinaConfig: ClusterPageConfig = {
  slug: 'web-contador-argentina',
  title: 'Web para contador en Argentina',
  description: 'Como deberia ser una web para contador en Argentina para explicar servicios, captar consultas y ordenar oportunidades.',
  keywords: 'web para contador argentina, pagina web contador argentina, sitio web estudio contable argentina',
  eyebrow: 'Profesionales',
  heroTitle: 'Web para contador en Argentina',
  heroHighlight: 'para captar consultas con claridad.',
  heroBody: 'En servicios contables, la web tiene que hacer simple algo que para muchos clientes ya es confuso. Si no ordena la propuesta, se pierden consultas valiosas.',
  introTitle: 'La claridad gana',
  introBody: 'Monotributo, impuestos, sueldos, sociedades o asesoria. Si el sitio no ayuda a ubicar rapido el problema del cliente, la conversion cae.',
  primaryTitle: 'Que deberia resolver una web contable',
  primaryItems: [
    { title: 'Servicios bien agrupados', description: 'Separar personas, pymes y tramites segun la logica comercial del estudio.' },
    { title: 'Propuesta entendible', description: 'Explicar que resuelven los servicios y para quien son, sin lenguaje interno.' },
    { title: 'Canal de contacto claro', description: 'Llevar al usuario a consulta, WhatsApp o diagnostico segun el tipo de necesidad.' },
  ],
  asideTitle: 'Tu web ordena o confunde?',
  asideBody: 'Podemos revisar si hoy tu sitio ayuda a captar mejores consultas o si obliga a explicar todo desde cero.',
  asidePrimaryCta: 'Pedir diagnostico para contador',
  issuesTitle: 'Errores frecuentes',
  issuesItems: [
    'Servicios mezclados sin segmentacion por tipo de cliente.',
    'Promesa demasiado tecnica o poco aterrizada a problemas reales.',
    'No mostrar una accion principal clara desde mobile.',
  ],
  nextStepsTitle: 'Que conviene ajustar',
  nextSteps: [
    { title: 'Agrupar por necesidad', description: 'Ordenar la oferta segun lo que busca cada perfil de cliente.' },
    { title: 'Simplificar mensaje', description: 'Hablar desde el problema del negocio y no desde el organigrama interno.' },
    { title: 'Seguir conversion', description: 'Medir que servicios y paginas generan contactos utiles.' },
  ],
  closingTitle: 'Una web contable efectiva ahorra explicaciones',
  closingBody: 'Cuando el sitio ordena la oferta y facilita contacto, el estudio recibe consultas mas claras y de mejor encaje.',
};

export const webArquitectoArgentinaConfig: ClusterPageConfig = {
  slug: 'web-arquitecto-argentina',
  title: 'Web para arquitecto en Argentina',
  description: 'Que necesita una web para arquitecto en Argentina para mostrar portfolio, generar confianza y abrir conversaciones comerciales.',
  keywords: 'web para arquitecto argentina, pagina web arquitecto argentina, sitio web estudio arquitectura argentina',
  eyebrow: 'Profesionales',
  heroTitle: 'Web para arquitecto en Argentina',
  heroHighlight: 'para mostrar criterio y generar consultas.',
  heroBody: 'En arquitectura, la web tiene que mostrar proyectos, proceso y mirada profesional. Si todo queda en una galeria linda pero muda, no convierte.',
  introTitle: 'El portfolio solo no alcanza',
  introBody: 'Las imagenes atraen, pero el cliente tambien necesita entender tipo de obra, enfoque, ubicacion y como avanzar a una primera conversacion.',
  primaryTitle: 'Que deberia resolver una web de arquitectura',
  primaryItems: [
    { title: 'Portfolio con contexto', description: 'Mostrar proyectos con informacion util, no solo fotos sueltas.' },
    { title: 'Posicionamiento profesional', description: 'Explicar enfoque, tipo de cliente y escala de trabajos para filtrar mejor.' },
    { title: 'Conversion clara', description: 'Guiar a una consulta inicial sin depender de que el usuario adivine el siguiente paso.' },
  ],
  asideTitle: 'Tu portfolio hoy convierte?',
  asideBody: 'Podemos revisar si tu sitio muestra bien el valor de tu estudio o si se queda corto para generar consultas.',
  asidePrimaryCta: 'Pedir diagnostico para arquitectura',
  issuesTitle: 'Lo que mas suele trabar',
  issuesItems: [
    'Portfolio sin contexto de proyecto, escala o tipo de cliente.',
    'Sitios visualmente correctos pero sin propuesta comercial clara.',
    'Contacto relegado a una pagina final que pocos visitan.',
  ],
  nextStepsTitle: 'Como mejorarlo',
  nextSteps: [
    { title: 'Curar casos', description: 'Elegir proyectos que mejor expliquen experiencia y valor comercial.' },
    { title: 'Contar proceso', description: 'Ayudar al cliente a entender como seria trabajar con vos.' },
    { title: 'Acercar el contacto', description: 'Integrar CTA y consulta en paginas donde el interes ya esta alto.' },
  ],
  closingTitle: 'Una web de arquitectura tiene que mostrar criterio y abrir negocio',
  closingBody: 'Si el sitio combina portfolio, claridad y accion, se vuelve una herramienta comercial y no solo una vidriera.',
};
