import type { ClusterPageConfig } from '@/features/content/cluster-content-page.types';

export const webInmobiliariaArgentinaConfig: ClusterPageConfig = {
  slug: 'web-inmobiliaria-argentina',
  title: 'Web inmobiliaria en Argentina',
  description: 'Qué necesita una web inmobiliaria en Argentina para captar consultas, mostrar propiedades y ordenar oportunidades.',
  keywords: 'web inmobiliaria argentina, pagina web inmobiliaria argentina, sitio web para inmobiliaria',
  eyebrow: 'Inmobiliarias',
  heroTitle: 'Web inmobiliaria en Argentina',
  heroHighlight: 'para mostrar propiedades y captar consultas.',
  heroBody: 'En una inmobiliaria, la web no puede ser solo institucional. Tiene que ayudar a encontrar propiedades, filtrar interés y facilitar contacto.',
  introTitle: 'La vitrina sola no alcanza',
  introBody: 'Si el usuario no entiende rápido qué ofrecés, dónde trabajás o cómo consultar, la web pierde valor comercial aunque tenga muchas propiedades cargadas.',
  primaryTitle: 'Qué debería resolver una web inmobiliaria',
  primaryItems: [
    { title: 'Propiedades bien presentadas', description: 'Fotos, ubicación, filtros y fichas claras para que el usuario no abandone rápido.' },
    { title: 'Consultas simples', description: 'Formularios, WhatsApp o CTA visibles para bajar fricción en cada publicación.' },
    { title: 'Marca y confianza', description: 'Mostrar equipo, zona de trabajo y experiencia para competir con portales y otras inmobiliarias.' },
  ],
  asideTitle: '¿Tu web hoy acompaña ventas?',
  asideBody: 'Podemos revisar si tu sitio ordena bien la oferta o si hoy está perdiendo consultas valiosas.',
  asidePrimaryCta: 'Pedir diagnóstico para inmobiliaria',
  issuesTitle: 'Qué suele fallar',
  issuesItems: [
    'Listado desordenado o difícil de navegar desde mobile.',
    'Propiedades sin contexto comercial claro.',
    'Pocas oportunidades de contacto en páginas de inmuebles.',
  ],
  nextStepsTitle: 'Cómo mejorarlo',
  nextSteps: [
    { title: 'Ordenar captación', description: 'Definir qué propiedades y búsquedas tienen más potencial comercial.' },
    { title: 'Mejorar navegación', description: 'Hacer fácil encontrar inmuebles por tipo, zona o intención.' },
    { title: 'Medir consultas', description: 'Entender qué páginas generan leads reales y cuáles no.' },
  ],
  closingTitle: 'Una inmobiliaria vende confianza y claridad',
  closingBody: 'Si el sitio muestra bien la oferta y hace simple consultar, la web deja de ser catálogo estático y pasa a trabajar para el negocio.',
};

export const portalPropiedadesDesarrolloWebConfig: ClusterPageConfig = {
  slug: 'portal-propiedades-desarrollo-web',
  title: 'Portal de propiedades y desarrollo web',
  description: 'Cuándo conviene desarrollar un portal de propiedades propio y qué tiene que resolver para no quedar corto desde el arranque.',
  keywords: 'portal propiedades desarrollo web, portal inmobiliario a medida, desarrollo portal inmuebles argentina',
  eyebrow: 'Portal inmobiliario',
  heroTitle: 'Portal de propiedades y desarrollo web',
  heroHighlight: 'cuando una web simple ya no alcanza.',
  heroBody: 'Un portal inmobiliario no es solo una web con más fichas. Necesita estructura, búsqueda, escalabilidad y operación real detrás.',
  introTitle: 'No es lo mismo que una web inmobiliaria',
  introBody: 'Cuando hay mucho volumen, múltiples tipos de propiedades o necesidad de filtros avanzados, la lógica cambia y la herramienta también.',
  primaryTitle: 'Qué debería resolver un portal propio',
  primaryItems: [
    { title: 'Búsqueda avanzada', description: 'Filtros, zonas, tipos de operación y navegación pensada para volumen de publicaciones.' },
    { title: 'Gestión ordenada', description: 'Cargar, actualizar y dar de baja propiedades sin romper la experiencia del usuario.' },
    { title: 'Escala comercial', description: 'Preparar la base para crecer sin depender de parches o estructura improvisada.' },
  ],
  asideTitle: '¿Ya estás en ese punto?',
  asideBody: 'Podemos revisar si te conviene un portal propio o si todavía alcanza con una estructura más simple.',
  asidePrimaryCta: 'Pedir diagnóstico para portal',
  issuesTitle: 'Problemas típicos',
  issuesItems: [
    'Querer resolver volumen con una web pensada para pocos inmuebles.',
    'Filtros malos o navegación lenta que espanta búsquedas.',
    'Cargas manuales que consumen tiempo y generan errores.',
  ],
  nextStepsTitle: 'Cómo encararlo',
  nextSteps: [
    { title: 'Definir alcance real', description: 'Separar qué necesita hoy el negocio y qué puede escalar después.' },
    { title: 'Diseñar arquitectura', description: 'Pensar búsqueda, categorías y carga con lógica de producto.' },
    { title: 'Evitar deuda temprana', description: 'No improvisar algo que en pocos meses haya que rehacer.' },
  ],
  closingTitle: 'Un portal propio tiene sentido cuando acompaña escala',
  closingBody: 'Si la herramienta se diseña para cómo trabajás y cómo busca tu cliente, el portal deja de ser un problema y se vuelve ventaja.',
};

export const crmInmobiliarioAMedidaConfig: ClusterPageConfig = {
  slug: 'crm-inmobiliario-a-medida',
  title: 'CRM inmobiliario a medida',
  description: 'Qué resuelve un CRM inmobiliario a medida y cuándo conviene frente a herramientas genéricas o planillas.',
  keywords: 'crm inmobiliario a medida, sistema inmobiliario a medida, crm para inmobiliaria argentina',
  eyebrow: 'CRM inmobiliario',
  heroTitle: 'CRM inmobiliario a medida',
  heroHighlight: 'cuando planillas y sistemas genéricos ya no alcanzan.',
  heroBody: 'El cuello de botella muchas veces no está en la captación sino en el seguimiento. Un CRM a medida ordena oportunidades, tareas y operación inmobiliaria.',
  introTitle: 'No todo se resuelve con software genérico',
  introBody: 'Si tu equipo ya trabaja con procesos propios, múltiples estados comerciales o necesidades de seguimiento particulares, una herramienta estándar puede quedar corta rápido.',
  primaryTitle: 'Qué debería resolver un CRM inmobiliario',
  primaryItems: [
    { title: 'Seguimiento comercial', description: 'Ordenar leads, propiedades, estados y tareas para que nada se pierda.' },
    { title: 'Visibilidad operativa', description: 'Saber qué está pasando con cada oportunidad sin depender de memoria o planillas sueltas.' },
    { title: 'Adaptación al negocio', description: 'Responder a tu forma de trabajo, no obligarte a adaptar todo al sistema.' },
  ],
  asideTitle: '¿Vale la pena hacerlo a medida?',
  asideBody: 'Podemos revisar si hoy tu operación inmobiliaria justifica una herramienta propia o si conviene otra etapa primero.',
  asidePrimaryCta: 'Pedir diagnóstico de CRM',
  issuesTitle: 'Señales de que hace falta',
  issuesItems: [
    'Leads y tareas repartidos entre WhatsApp, Excel y notas.',
    'No hay visibilidad clara del pipeline comercial.',
    'El equipo pierde tiempo repitiendo carga o buscando información.',
  ],
  nextStepsTitle: 'Cómo decidirlo',
  nextSteps: [
    { title: 'Mapear procesos', description: 'Entender qué flujo necesitás ordenar y qué métricas importan.' },
    { title: 'Separar esencial de deseable', description: 'Definir un MVP útil antes de construir todo el sistema ideal.' },
    { title: 'Integrar con captación', description: 'Conectar CRM, web y consultas para que la información fluya.' },
  ],
  closingTitle: 'Un CRM a medida tiene sentido si ahorra caos',
  closingBody: 'Cuando la operación inmobiliaria gana orden y visibilidad, el equipo vende mejor y depende menos de soluciones improvisadas.',
};
