[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/image_perfil.jpg"
  to = "/image_perfil.jpg"
  status = 200

[[headers]]
  for = "/image_perfil.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 